import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientUUID from "./components/ClientUUID";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata = {
  title: "ADB Web manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientUUID />
        {children}
      </body>
    </html>
  );
}